//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SliceOfPie_Model.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaDataType
    {
        public MetaDataType()
        {
            this.FileMetaDatas = new HashSet<FileMetaData>();
        }
    
        public string Type { get; set; }
    
        public virtual ICollection<FileMetaData> FileMetaDatas { get; set; }
    }
}
