//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SliceOfPie_Model.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Files = new HashSet<File>();
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
